//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnowTrolleyProduction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditoria_Respuestas
    {
        public int Id { get; set; }
        public Nullable<int> PreguntaId { get; set; }
        public Nullable<int> AuditoriaId { get; set; }
        public Nullable<bool> Respuesta { get; set; }
    
        public virtual Auditoria Auditoria { get; set; }
        public virtual Checklist_Preguntas Checklist_Preguntas { get; set; }
    }
}
