//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnowTrolleyProduction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checklist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Checklist()
        {
            this.Auditorias = new HashSet<Auditoria>();
            this.Checklist_Respuestas = new HashSet<Checklist_Respuestas>();
        }
    
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> Contestado_Por { get; set; }
        public Nullable<int> Equipo_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auditoria> Auditorias { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Equipos Equipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Checklist_Respuestas> Checklist_Respuestas { get; set; }
    }
}
