//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnowTrolleyProduction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeFullInfo
    {
        public int EmployeeID { get; set; }
        public bool EmployeeStatus { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string EmployeeNumber { get; set; }
        public string EmployeeStampNumber { get; set; }
        public string Name { get; set; }
        public string FatherLastName { get; set; }
        public string MotherLastName { get; set; }
        public string FullName { get; set; }
        public string NameViewChar { get; set; }
        public Nullable<int> EmployeeReportToID { get; set; }
        public string EmployeeReportToNumber { get; set; }
        public string ReportToName { get; set; }
        public string JobTitleName { get; set; }
        public string DepartmentName { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Code { get; set; }
        public string EmployeeType { get; set; }
        public string Email { get; set; }
        public string MobilePhone { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string PersonalPhone { get; set; }
        public string Gender { get; set; }
        public string BloodType { get; set; }
        public string Scholarship { get; set; }
        public Nullable<int> ChildrenNumber { get; set; }
        public Nullable<int> EconomicDependents { get; set; }
        public string ContractTypeName { get; set; }
        public string ClassName { get; set; }
        public string BuildingName { get; set; }
        public string MaritalStatus { get; set; }
        public Nullable<int> LineID { get; set; }
        public string Line { get; set; }
        public bool ShowInOrgChart { get; set; }
        public Nullable<bool> StatusTraining { get; set; }
        public string Extension { get; set; }
        public Nullable<int> ShiftBAE { get; set; }
        public Nullable<int> ShiftID { get; set; }
    }
}
