//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnowTrolleyProduction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Id_Status
    {
        public int Id_Status1 { get; set; }
        public string Description { get; set; }
        public string Campo1 { get; set; }
    }
}
