//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnowTrolleyProduction.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BAESystemsGuaymasEntities : DbContext
    {
        public BAESystemsGuaymasEntities()
            : base("name=BAESystemsGuaymasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acomodo> Acomodoes { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Ensamble> Ensambles { get; set; }
        public virtual DbSet<Equipos> Equipos { get; set; }
        public virtual DbSet<Linea> Lineas { get; set; }
        public virtual DbSet<Maquina> Maquinas { get; set; }
        public virtual DbSet<Programa> Programas { get; set; }
        public virtual DbSet<TrolleySetup> TrolleySetups { get; set; }
        public virtual DbSet<Id_Status> Id_Status { get; set; }
        public virtual DbSet<Work> Works { get; set; }
        public virtual DbSet<Works_Backup> Works_Backup { get; set; }
        public virtual DbSet<FiscalCalendar> FiscalCalendars { get; set; }
        public virtual DbSet<Trolley_Program> Trolley_Program { get; set; }
    }
}
