//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnowTrolleyProduction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Auditorias = new HashSet<Auditoria>();
            this.Checklists = new HashSet<Checklist>();
        }
    
        public int EmployeeID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> JobTitleID { get; set; }
        public string EmployeeNumber { get; set; }
        public string EmployeeStampNumber { get; set; }
        public string Name { get; set; }
        public string FatherLastName { get; set; }
        public string MotherLastName { get; set; }
        public string NameViewChar { get; set; }
        public int ShiftID { get; set; }
        public string Email { get; set; }
        public string MobilePhone { get; set; }
        public string Extension { get; set; }
        public string Location { get; set; }
        public bool EmployeeStatus { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<int> EmployeeClassID { get; set; }
        public Nullable<int> EmployeeContractTypeID { get; set; }
        public Nullable<int> LineID { get; set; }
        public Nullable<int> EmployeeTypeID { get; set; }
        public Nullable<int> BuildingID { get; set; }
        public System.DateTime RecordAddedDate { get; set; }
        public bool RecordDeleted { get; set; }
        public Nullable<System.DateTime> RecordDeletedDate { get; set; }
        public string PasswordHash { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auditoria> Auditorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Checklist> Checklists { get; set; }
    }
}
