//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnowTrolleyProduction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Id { get; set; }
        public string Id_status { get; set; }
        public string Equipo { get; set; }
        public string Usuario { get; set; }
        public string No_part { get; set; }
        public string WorkOrder { get; set; }
        public string Description { get; set; }
        public string Accion_correctiva { get; set; }
        public string Falla_Tecnico { get; set; }
        public string No_Operador { get; set; }
        public Nullable<System.DateTime> Fecha_Reporte { get; set; }
        public string Nombre_Modifico { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public string Nombre_Cierre { get; set; }
        public Nullable<System.DateTime> Fecha_Cierre { get; set; }
        public string Contribuidor { get; set; }
        public string Urgent { get; set; }
        public Nullable<double> Tiempo_atencion { get; set; }
        public Nullable<int> Week_apertura { get; set; }
        public Nullable<int> Week_cierre { get; set; }
        public string Comentarios { get; set; }
        public Nullable<int> AreaId { get; set; }
    }
}
